input {
  beats {
    port => 5044
  }
}

filter {
  date {
    match => ["datetime", "ISO8601"]
    target => "@timestamp"
  }

  mutate {
    remove_field => ["agent", "ecs", "input", "log", "tags"]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "medarea-logs-%{+YYYY.MM.dd}"
  }
}
